language: dart
dart:
  - stable
  - beta
before_script:
  - pub global activate coverage
dart_task:
  - test: --platform vm --coverage=coverage
  - test: --platform chrome
  - dartanalyzer: --fatal-warnings lib
after_success:
  - pub global run coverage:format_coverage --packages=.packages -i coverage/test/immutable_model_test.dart.vm.json --report-on lib --lcov --out coverage/lcov.txt
  - bash <(curl -s https://codecov.io/bash) -f coverage/lcov.txt
cache:
  directories:
    - $HOME/.pub-cache
branches:
  only: [master]
