name: immutable_model
description: immutable_model helps you write an authoritative and safe domain layer. Easily define valid, hierarchical immutable state models with an expressive API for updating state data and transitioning between states. Built on top of built_collection and uses Equatable.
version: 0.5.0
homepage: https://github.com/oliverfunk/immutable_model

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  built_collection: ^4.3.2
  equatable: ^1.2.0
  logging: ^0.11.4
  meta: ^1.1.8
  crypto: ^2.1.5

dev_dependencies:
  test:
