name: immutable_model
description: Define valid, hierarchical immutable state models with an expressive API for updating state data and transitioning between states.
version: 0.7.0
homepage: https://github.com/oliverfunk/immutable_model

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  built_collection: ^4.3.2
  equatable: ^1.2.0
  logging: ^0.11.4
  meta: ^1.1.8
  crypto: ^2.1.5

dev_dependencies:
  effective_dart: ^1.2.0
  test:
