name: immutable_model
description: Define valid, hierarchical immutable state models with an expressive API for updating state data and transitioning between states.
version: 0.10.0-nullsafety.0
homepage: https://github.com/oliverfunk/immutable_model

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  valid: ^0.2.0-nullsafety
  equatable: ^2.0.0-nullsafety
  meta: ^1.3.0-nullsafety

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test:
