name: immutable_model
description: Library for creating immutable, hierarchical and valid models quickly and easily
version: 0.0.5
author: Oliver Funk <oli.funk@gmail.com>
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  built_collection: ^4.3.2
  equatable: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter